---
output:
  pdf_document: default
  html_document: default
---
# Example R Markdown Documen

Install Tidyverse Package

```{r}
if (!requireNamespace("tidyverse", quietly = TRUE)) {
  install.packages("tidyverse")
}

library(tidyverse)
```

Clear the Environment
```{r}
rm(list = ls())
```

Set the Working Directory

```{r}
setwd("~/Projects/eco324_ps1")
```

Load the Data

```{r}
data <- read.csv("verboven_cars.csv")
```

Summary Statistics

```{r}
summary(data)
```

Rename a variable

```{r}
data <- data %>%
  rename(year = ye,
         country = ma,
         population = pop,
         horsepower = hp,
         fuel = li,
         width = wi,
         height = he,
         weight = we,
         demographic = home,
         quantity = qu)
```

Generate a new variable based on existing variables

```{r}
data <- data %>%
  mutate(market_size = population/4) %>%
  # calculate market share s_j
  mutate(s_j = quantity/(market_size)) %>%
  # calculate the outside option market share s_0
  # which is 1 - sum(s_j) by year and country
  group_by(year, country) %>%
  mutate(s_0 = 1 - sum(s_j)) %>%
  ungroup() %>%
  # calculate y = log(s_j) - log(s_0)
  mutate(y = log(s_j) - log(s_0))
```

Install the `fixest` package for fixed effects regression

```{r}
# Install fixest if not already installed
if (!requireNamespace("fixest", quietly = TRUE)) {
  install.packages("fixest")
}

library(fixest)
```

